spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine
    username: se_user
    password: se_user
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
logging:
  level:
    root: WARN

forSitesThreadNumber: 12
forPagesThreadNumber: 16
forIndexesThreadNumber: 16
repeatedPageCount: 14
maxPagesInSite: 4000

isFirstStagePresent: true

sites:
  - url: http://www.playback.ru
    name: PlayBack.ru
  - url: https://volochek.life
    name: Вышний Волочёк
  - url: http://radiomv.ru
    name: Милицейкая волна
#  - url: https://ipfran.ru
#    name: Институт прикладной физики Российской академии наук
  - url: https://dimonvideo.ru
    name: DIMONVIDEO
  - url: https://nikoartgallery.com
    name: Niko ART GALLERY
  - url: https://et-cetera.ru/mobile
    name: Театр «Et Cetera»
  - url: https://www.lutherancathedral.ru
    name: Кафедральный собор святых Петра и Павла
  - url: https://dombulgakova.ru
    name: Булгаковскiй домъ
  - url: https://www.svetlovka.ru
    name: Светловка
  - url: https://www.lenta.ru
    name: Лента.ру
